platform:ios, '8.0'

use_frameworks!

target 'XJHQRScanKit_Example' do
  pod 'XJHQRScanKit', :path => '../'
  
  pod 'Masonry', '~> 1.1.0'
  pod 'ReactiveObjC', '~> 3.1.0'
  pod 'MLeaksFinder', '~> 1.0.0'

  target 'XJHQRScanKit_Tests' do
    inherit! :search_paths

    
  end
end
